feat(landings): add landings by targets
SocialGouv/mon-psy-sante pull request #36
Opened 2022-01-25 08:17 UTC by carolineBda

2022-02-15 14:52 UTC, desoindx requested changes
Would be nice to use all the react-dsfr components to avoid all this classes
Spacing of block needs to be reviewed
Some content are not responsive at all
Lot of duplication, the 4 pages basically have the same design but nothing is mutualized. It will be a huge mess when we'll need to make changes

2022-02-15 14:52 UTC, desoindx commented on .eslintrc.json
> +    "jsx-a11y/media-has-caption": "off",
it's gonna be an issue on the accessibility audit

2022-02-15 14:52 UTC, desoindx commented on cypress/integration/home.spec.js
> +    cy.get("h2 a").first().click();
can you identify specificaly this h2
this test will break at the moment we change an h2 on the page :/

2022-02-15 14:52 UTC, desoindx commented on cypress/integration/home.spec.js
> +  it("robots.txt should be visible", () => {
This has nothing to do here

2022-02-15 14:52 UTC, desoindx commented on cypress/integration/home.spec.js
> +describe("Home & landing pages", () => {
I don't really get the point of those e2e test ?

2022-02-15 14:52 UTC, desoindx commented on src/components/VideoButon.tsx
> +      <button
Can you use a button from react dsfr ?

2022-02-15 14:52 UTC, desoindx commented on src/pages/_app.tsx
> -        </Head>
No headtag here ? risky if we forget it on a new page :/

2022-02-15 14:52 UTC, desoindx commented on src/pages/index.tsx
> +            <div className="fr-col-12 fr-col-md-6">
You can use Row and Col from the react dsfr

2022-02-15 14:52 UTC, desoindx commented on src/pages/index.tsx
> +      <section>
The spacings of all those section are quite eratics...

2022-02-15 14:52 UTC, desoindx commented on src/pages/index.tsx
> +            <div className="fr-col-12 fr-col-md-5">
not responsive 
<img width="762" alt="image" src="https://user-images.githubusercontent.com/5389328/154079019-aa60f28e-5485-4352-8bfd-c20f70292917.png">

2022-02-15 14:52 UTC, desoindx commented on src/pages/index.tsx
> +            <div className="fr-col-12">
not responsive 
<img width="782" alt="image" src="https://user-images.githubusercontent.com/5389328/154079097-7edecea1-9d62-4cf6-acbe-2ef22f50555d.png">

2022-02-15 14:52 UTC, desoindx commented on src/pages/patients.tsx
> +                <VideoButton onClick={() => setVideo("show")} />
The video is not loading on my computer: 'Refused to load media from 'http://localhost:3000/images/Video-MonPsy.mp4' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.'

2022-02-15 14:52 UTC, desoindx commented on src/pages/patients.tsx
> +              <h2>Quel est le rôle du médecin&nbsp;?</h2>
not really responsive on mobile 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/5389328/154079808-03a90040-af85-4a57-bb22-a2adf4e31e00.png">

2022-02-15 14:52 UTC, desoindx commented on src/pages/patients.tsx
> +              <div className="fr-card fr-centered fr-card--no-arrow">
not responsive 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/5389328/154080021-4b91abec-803e-49f7-82e9-e318d11e88b1.png">

2022-02-15 14:52 UTC, desoindx commented on src/pages/index.tsx
> +                  <img src="/images/cnam.png" alt="Logo CNAM" height="140" />
This logo have a white background so the hover does not show the background in grey whereas it does on the Sante-publique-France-logo

2022-02-15 14:52 UTC, desoindx commented on src/pages/index.tsx
> +                  <img src="/images/cnam.png" alt="Logo CNAM" height="140" />
and the quality of this logo is quite bad 
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/5389328/154081158-4561ec91-d246-40cb-b3c1-4ea264c6f2df.png">

2022-02-15 15:35 UTC, carolineBda commented on cypress/integration/home.spec.js
> +  it("robots.txt should be visible", () => {
where would you test robots.txt ?

2022-02-15 15:38 UTC, carolineBda commented on cypress/integration/home.spec.js
> +    cy.get("h2 a").first().click();
fine for now

2022-02-15 15:38 UTC, carolineBda commented on src/components/VideoButon.tsx
> +      <button
yes :+1:

2022-02-15 15:44 UTC, carolineBda commented on src/pages/index.tsx
> +                  <img src="/images/cnam.png" alt="Logo CNAM" height="140" />
je le trouve pas sur internet je vais leur demander

2022-02-15 16:02 UTC, carolineBda commented
> Would be nice to use all the react-dsfr components to avoid all this classes Spacing of block needs to be reviewed Some content are not responsive at all Lot of duplication, the 4 pages basically have the same design but nothing is mutualized. It will be a huge mess when we'll need to make changes

Thanks for feedbacks it is way better in mobile. 
I have moved some components to react-dsfr, I'll try to move more as I go (espacially the grid system)

2022-02-15 16:03 UTC, carolineBda commented on src/pages/patients.tsx
> +              <div className="fr-card fr-centered fr-card--no-arrow">
this one is hard, it is only on a certain breakpoint and I'm not sure the best way to handle it. 
Any suggestions ?

2022-02-16 08:26 UTC, carolineBda commented on src/pages/patients.tsx
> +              <div className="fr-card fr-centered fr-card--no-arrow">
fixed

2022-02-16 08:27 UTC, carolineBda commented
> Spacing of block needs to be reviewed

@desoindx I'm sure what you mean by : " Spacing of block needs to be reviewed" ? Is it ok now ?

2022-02-16 20:34 UTC, desoindx reviewed
Ill check the spaces on monday

2022-02-17 06:30 UTC, merged